In [1]:
import tensorflow as tf
import numpy as np

In [3]:
record_defaults=[0, np.nan, tf.constant(np.nan, dtype=tf.float64), "Hello", tf.constant([])]
parsed_fields = tf.io.decode_csv('1,2,3,4,5', record_defaults)
parsed_fields

2022-11-20 17:49:53.449488: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-11-20 17:49:53.452483: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-20 17:49:53.455530: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


[<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'4'>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>]

In [4]:
parsed_fields = tf.io.decode_csv(',,,,5', record_defaults)
parsed_fields


[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=nan>,
 <tf.Tensor: shape=(), dtype=float64, numpy=nan>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>]

In [5]:
from sklearn.datasets import load_sample_images

img = load_sample_images()["images"][0]

In [ ]:
data = tf.io.encode_jpeg(img)
data

In [2]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

2022-10-30 10:20:44.329736: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-10-30 10:20:44.331891: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-30 10:20:44.334980: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


<TensorSliceDataset shapes: (), types: tf.int32>

In [3]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [4]:
dataset = dataset.repeat(3).batch(7)
for item in dataset:
    print(item)


tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [5]:
dataset = dataset.map(lambda x: x**2, num_parallel_calls=4)
for item in dataset:
    print(item)

tf.Tensor([ 0  1  4  9 16 25 36], shape=(7,), dtype=int32)
tf.Tensor([49 64 81  0  1  4  9], shape=(7,), dtype=int32)
tf.Tensor([16 25 36 49 64 81  0], shape=(7,), dtype=int32)
tf.Tensor([ 1  4  9 16 25 36 49], shape=(7,), dtype=int32)
tf.Tensor([64 81], shape=(2,), dtype=int32)


2022-10-30 10:20:44.561053: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-10-30 10:20:44.581411: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2099940000 Hz


In [6]:
dataset = dataset.unbatch()
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(49, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(49, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(49,

In [7]:
dataset = dataset.filter(lambda x: x < 10)
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [8]:
for item in dataset.take(3):
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [9]:
train_filepaths = [f"datasets/train0{i}.csv" for i in range(1, 6)]
train_filepaths

['datasets/train01.csv',
 'datasets/train02.csv',
 'datasets/train03.csv',
 'datasets/train04.csv',
 'datasets/train05.csv']

In [10]:
filepath_dataset = tf.data.Dataset.list_files(train_filepaths, seed=42)
filepath_dataset

<ShuffleDataset shapes: (), types: tf.string>

In [11]:
for item in filepath_dataset:
    print(item)

tf.Tensor(b'datasets/train01.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/train05.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/train02.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/train04.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/train03.csv', shape=(), dtype=string)


In [12]:
n_readers = 5
dataset = filepath_dataset.interleave(
    lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
    cycle_length=n_readers,
)
dataset

<InterleaveDataset shapes: (), types: tf.string>

In [13]:
for item in dataset:
    print(item)

tf.Tensor(b'143.208.230.15 lacnic', shape=(), dtype=string)
tf.Tensor(b'109.182.81.87 ripencc', shape=(), dtype=string)
tf.Tensor(b'101.102.133.63 apnic', shape=(), dtype=string)
tf.Tensor(b'102.35.223.140 afrinic', shape=(), dtype=string)
tf.Tensor(b'11.106.190.79 arin', shape=(), dtype=string)
tf.Tensor(b'131.0.44.151 lacnic', shape=(), dtype=string)
tf.Tensor(b'109.163.253.139 ripencc', shape=(), dtype=string)
tf.Tensor(b'119.64.222.174 apnic', shape=(), dtype=string)
tf.Tensor(b'102.25.182.162 afrinic', shape=(), dtype=string)
tf.Tensor(b'100.246.16.16 arin', shape=(), dtype=string)
tf.Tensor(b'131.255.199.148 lacnic', shape=(), dtype=string)
tf.Tensor(b'109.231.179.25 ripencc', shape=(), dtype=string)
tf.Tensor(b'101.203.61.64 apnic', shape=(), dtype=string)
tf.Tensor(b'102.47.156.8 afrinic', shape=(), dtype=string)
tf.Tensor(b'107.7.218.14 arin', shape=(), dtype=string)
tf.Tensor(b'131.0.170.57 lacnic', shape=(), dtype=string)
tf.Tensor(b'109.151.67.28 ripencc', shape=(), dtype=s

In [14]:
dataset = dataset.shuffle(buffer_size=3)
for item in dataset:
    print(item)

tf.Tensor(b'109.182.81.87 ripencc', shape=(), dtype=string)
tf.Tensor(b'11.106.190.79 arin', shape=(), dtype=string)
tf.Tensor(b'101.102.133.63 apnic', shape=(), dtype=string)
tf.Tensor(b'100.246.16.16 arin', shape=(), dtype=string)
tf.Tensor(b'102.35.223.140 afrinic', shape=(), dtype=string)
tf.Tensor(b'109.163.253.139 ripencc', shape=(), dtype=string)
tf.Tensor(b'143.208.230.15 lacnic', shape=(), dtype=string)
tf.Tensor(b'119.64.222.174 apnic', shape=(), dtype=string)
tf.Tensor(b'107.7.218.14 arin', shape=(), dtype=string)
tf.Tensor(b'109.231.179.25 ripencc', shape=(), dtype=string)
tf.Tensor(b'131.0.44.151 lacnic', shape=(), dtype=string)
tf.Tensor(b'102.25.182.162 afrinic', shape=(), dtype=string)
tf.Tensor(b'101.203.61.64 apnic', shape=(), dtype=string)
tf.Tensor(b'102.47.156.8 afrinic', shape=(), dtype=string)
tf.Tensor(b'131.255.199.148 lacnic', shape=(), dtype=string)
tf.Tensor(b'109.151.67.28 ripencc', shape=(), dtype=string)
tf.Tensor(b'131.0.170.57 lacnic', shape=(), dtype=s

In [15]:
dataset.batch

<bound method DatasetV2.batch of <ShuffleDataset shapes: (), types: tf.string>>

In [16]:
n_inputs = 8
defs = [0.] * n_inputs + [tf.constant([], dtype=tf.float32)]
defs

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 <tf.Tensor: shape=(0,), dtype=float32, numpy=array([], dtype=float32)>]

In [17]:
tf.stack

<function tensorflow.python.ops.array_ops.stack(values, axis=0, name='stack')>

TF Records

In [18]:
with tf.io.TFRecordWriter("my_data.tfrecord") as f:
    f.write(b"This is the first record")
    f.write(b"And this is the second record")

In [19]:
filepaths = ["my_data.tfrecord"]
dataset = tf.data.TFRecordDataset(filepaths)
for item in dataset:
    print(item)

tf.Tensor(b'This is the first record', shape=(), dtype=string)
tf.Tensor(b'And this is the second record', shape=(), dtype=string)


Embeddings

In [4]:

vocab = ["<1H OCEAN", "INLAND", "NEAR OCEAN", "NEAR BAY", "ISLAND"]
indices = tf.range(len(vocab), dtype=tf.int64)
table_init = tf.lookup.KeyValueTensorInitializer(vocab, indices)
num_oov_buckets = 2
table = tf.lookup.StaticVocabularyTable(table_init, num_oov_buckets)

In [2]:
num_oov_buckets = 2
embedding_dim = 2
embed_init = tf.random.uniform([len(vocab) + num_oov_buckets, embedding_dim])
embedding_matrix = tf.Variable(embed_init)

2022-11-06 11:48:15.900135: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-11-06 11:48:15.902455: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-06 11:48:15.905738: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [3]:
embedding_matrix

<tf.Variable 'Variable:0' shape=(7, 2) dtype=float32, numpy=
array([[0.3461361 , 0.38232267],
       [0.69162285, 0.6161684 ],
       [0.9946238 , 0.75492716],
       [0.12662959, 0.7484466 ],
       [0.87431633, 0.89529157],
       [0.6687441 , 0.4083786 ],
       [0.7331686 , 0.41069627]], dtype=float32)>

In [5]:
categories = tf.constant(["NEAR BAY", "DESERT", "INLAND", "INLAND"])
cat_indices = table.lookup(categories)
cat_indices

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 5, 1, 1])>

In [6]:
tf.nn.embedding_lookup(embedding_matrix, cat_indices)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.12662959, 0.7484466 ],
       [0.6687441 , 0.4083786 ],
       [0.69162285, 0.6161684 ],
       [0.69162285, 0.6161684 ]], dtype=float32)>

In [7]:
embedding = tf.keras.layers.Embedding(input_dim=len(vocab) + num_oov_buckets,
                                      output_dim=embedding_dim)
embedding(cat_indices)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.01509653, -0.02175293],
       [ 0.03029987, -0.04906092],
       [-0.01422281,  0.01884592],
       [-0.01422281,  0.01884592]], dtype=float32)>

In [ ]:
regular_inputs = tf.keras.layers.Input(shape=[8])
categories = tf.keras.layers.Input(shape=[], dtype=tf.string)
cat_indices = tf.keras.layers.Lambda(lambda cats: table.lookup(cats))(categories)
cat_embed = tf.keras.layers.Embedding(input_dim=7, output_dim=2)(cat_indices)
encoded_inputs = tf.keras.layers.concatenate([regular_inputs, cat_embed])
outputs = tf.keras.layers.Dense(1)(encoded_inputs)
model = tf.keras.models.Model(inputs=[regular_inputs, categories],
                              outputs=[outputs])